application: node-420
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+ 
  script: backend.main.app
  login: admin

- url: /.*
  script: backend.main.app

libraries:
- name: webapp2
  version: "latest"

- name: "jinja2"
  version: "latest"
